export const data = {
  name: "Avinash Magar",
  fullName: "Avinash Sanjay Magar",
  email: "avinashmagar15@gmail.com",
  phone: "+91 70587 00755",
  linkedin: "https://www.linkedin.com/in/avinash-magar-1ba853168/",
  github: "https://github.com/",
  typewriterWords: [
    "Flutter apps",
    "React UIs",
    "mobile apps",
    "ML models",
    "iOS apps",
    "web apps",
  ],

  stats: [
    { num: 10, suffix: "+", label: "Companies" },
    { num: 50, suffix: "+", label: "Projects" },
    { num: "8.56", suffix: "", label: "CGPA" },
  ],

  about: [
    "I'm a developer who loves the full spectrum of building software — from crafting pixel-perfect mobile UIs in Flutter to wiring up backends and training machine learning models.",
    "With experience spanning Android, iOS, Flutter, React, and ML/AI, I've shipped real products at companies across India — Gurugram, Hyderabad, Chennai, Aurangabad, and Pune.",
    "B.Tech in Information Technology from VIIT Pune, CGPA 8.56. Always looking for the next challenge.",
  ],

  education: [
    {
      degree: "B.Tech — Information Technology",
      school: "Vishwakarma Institute of Information Technology, Pune",
      period: "Dec 2019 – May 2023",
      grade: "CGPA: 8.56",
      color: "green",
    },
    {
      degree: "Diploma — Computer Engineering",
      school: "Government Polytechnic, Aurangabad",
      period: "July 2015 – Nov 2019",
      grade: "66.20%",
      color: "green",
    },
    {
      degree: "Certification",
      school: "Data Science & Engineering",
      period: "K P Infotech",
      grade: null,
      color: "amber",
    },
  ],

  skills: [
    {
      icon: "📱",
      title: "Mobile Development",
      pills: [
        "Flutter",
        "Dart",
        "Android (Java)",
        "iOS (Objective-C)",
        "GetX",
        "Riverpod",
        "Provider",
        "MVVM",
        "REST APIs",
      ],
    },
    {
      icon: "🌐",
      title: "Web Development",
      pills: [
        "React JS",
        "Next.js",
        "Node.js",
        "JavaScript",
        "HTML & CSS",
        "Tailwind",
        "Bootstrap",
        "FastAPI",
        "Flask",
      ],
    },
    {
      icon: "🤖",
      title: "ML / Data Science",
      pills: [
        "Python",
        "TensorFlow",
        "PyTorch",
        "scikit-learn",
        "Pandas",
        "NumPy",
        "Seaborn",
        "Streamlit",
        "Power BI",
      ],
    },
    {
      icon: "🛠",
      title: "Tools & Databases",
      pills: [
        "Git & GitHub",
        "VS Code",
        "Android Studio",
        "Xcode",
        "Firebase",
        "MySQL",
        "SQLite",
        "TestFlight",
        "Google Colab",
      ],
    },
  ],

  experience: [
    {
      company: "S IT Solutions PVT LTD",
      role: "Trainee Flutter Developer",
      period: "Aug 2025 – Present",
      location: "Pune, Maharashtra",
      points: [
        "Built responsive UI from Figma designs for Android & iOS platforms.",
        "Integrated third-party SDKs and REST APIs for seamless app functionality.",
        "Added packages to enhance app performance and overall UX quality.",
      ],
    },
    {
      company: "Trueview India",
      role: "Engineer – Android & iOS",
      period: "May 2025 – Jul 2025",
      location: "Aurangabad, Maharashtra",
      points: [
        "Built and deployed apps using Native Android with Java.",
        "Developed and published cross-platform apps using Flutter.",
        "Created and deployed native iOS apps using Objective-C.",
      ],
    },
    {
      company: "Recipto PVT LTD",
      role: "Software Intern",
      period: "Nov 2024 – Apr 2025",
      location: "Hyderabad, Telangana",
      points: [
        "Collaborated with senior developers to design, implement, and test new features.",
        "Contributed to the development of the Recipto app.",
        "Deployed iOS apps via TestFlight and App Store for public release.",
      ],
    },
    {
      company: "Verdant Info Comm Systems",
      role: "Flutter Developer Intern",
      period: "Feb 2024 – May 2024",
      location: "Chennai, India",
      points: [
        "Worked on the Bahrain app using Flutter alongside a senior developer.",
        "Built and tested responsive UI components for cross-platform use.",
        "Assisted in cross-platform UI debugging and fixes.",
      ],
    },
    {
      company: "Warehow Technologies",
      role: "Full Stack Developer",
      period: "Aug 2023 – Feb 2024",
      location: "Gurugram, India",
      points: [
        "Built a cross-platform social media & shopping app using Flutter for Android and iOS.",
        "Integrated REST APIs for authentication, posts, and real-time updates.",
        "Developed responsive UI from Figma designs using Flutter widgets.",
      ],
    },
  ],

  projects: [
    {
      num: "01",
      name: "ThoughtVault",
      desc: "A personal journaling and note-taking app published on the Google Play Store. Built with Flutter for a smooth, cross-platform experience with a clean and intuitive UI.",
      tech: ["Flutter", "Dart", "Android", "Play Store"],
      link: "https://play.google.com/store/apps/details?id=com.avinashmagar.thoughtvault",
      playStore: true,
    },
    {
      num: "02",
      name: "Restart",
      desc: "A published Android app available on Google Play Store. Built with Flutter featuring engaging gameplay mechanics and a polished mobile-first user experience.",
      tech: ["Flutter", "Dart", "Android", "Play Store"],
      link: "https://play.google.com/store/apps/details?id=com.hardmode.restart",
      playStore: true,
    },
    {
      num: "03",
      name: "BMI Calculator",
      desc: "A clean and accurate BMI Calculator app live on the Google Play Store. Built with Flutter, featuring instant calculations, health category display, and a minimal UI.",
      tech: ["Flutter", "Dart", "Android", "Play Store"],
      link: "https://play.google.com/store/apps/details?id=com.avinash.bmi_calculator",
      playStore: true,
    },
    {
      num: "04",
      name: "Samachar App",
      desc: "Real-time news app built with Flutter and MVVM architecture. Integrates NewsAPI for categorized news (business, tech, sports) with Provider state management.",
      tech: ["Flutter", "Dart", "MVVM", "NewsAPI", "Provider"],
      link: "#",
      playStore: false,
    },
    {
      num: "05",
      name: "Todo App",
      desc: "Offline-first native Android app with SQLite for full CRUD operations. Features a dynamic custom RecyclerView UI and clean modular architecture.",
      tech: ["Android", "Java", "SQLite", "RecyclerView"],
      link: "#",
      playStore: false,
    },
    {
      num: "06",
      name: "Quiz App",
      desc: "Cross-platform quiz application built with Flutter. Features responsive UI/UX, dynamic question flow, and a final score summary screen.",
      tech: ["Flutter", "Dart", "GitHub"],
      link: "#",
      playStore: false,
    },
  ],
};
